
defaults:
  - _self_

encoder: 'jukebox'
mode: 'train'
recompute: False

train:
  batch_size: 8
  epochs: 5
  

eval:
  batch_size: 8

model:
  learning_rate: 0.001

gpu: 6

distributed:
  masterport: '12355'

# config.yaml


hydra:  
  output_subdir: null  
  run:  
    dir: .