
defaults:
  - _self_

encoder: 'jukebox'
mode: 'train'
recompute: False
epochs: 5

dataset:
  pair_mode: 'once'
  train:
    batch_size: 8
    num_workers: 4
    shuffle: True
  eval:
    batch_size: 8
    shuffle: False
  test:
    batch_size: 8
    shuffle: False

model:
  learning_rate: 0.001

gpu: 6

distributed:
  masterport: '12355'

# config.yaml


hydra:  
  output_subdir: null  
  run:  
    dir: .