task: 'diff'
encoder: 'dac'
use_trained: False
mode: 'train'
recompute: False
epochs: 5
random_seed: 13
max_epochs: 500
learning_rate: 5e-5
objective: 'classification' # 'regression'
max_segs: 30  # each audio encoding segment is 10s. 30 segments = 5 minutes

dataset:
  num_classes: 9
  n_segs: 30
  train:
    batch_size: 8
    num_workers: 0
    shuffle: True
  eval:
    batch_size: 8
    shuffle: False
  test:
    batch_size: 2
    shuffle: False

defaults:
  - model: AudioCNNTransformer

gpu: [6]

distributed:
  masterport: '12356'

# config.yaml


hydra:  
  output_subdir: null  
  run:  
    dir: .