task: 'technique'
encoder: 'spec'
use_trained: False
mode: 'train'
recompute: False
epochs: 5
random_seed: 13
max_epochs: 500
learning_rate: 5e-6
weight_decay: 1e-5
objective: 'multi-label classification' 
max_segs: 30  # each audio encoding segment is 10s. 30 segments = 5 minutes

dataset:
  pos_weight: [3.625, 4.55, 6.16, 5.34, 5.16, 5.34, 4.41]
  num_classes: 7
  pair_mode: 'once'
  n_segs: 30
  train:
    batch_size: 12
    num_workers: 12
    shuffle: True
  eval:
    batch_size: 12
    num_workers: 12
    shuffle: True
  test:
    batch_size: 24
    num_workers: 12
    shuffle: False
  

defaults:
  - model: AudioCNNTransformer

gpu: [0]

distributed:
  masterport: '12355'

# config.yaml


hydra:  
  output_subdir: null  
  run:  
    dir: .